language: node_js
node_js: 
  - "12"
services:
  - docker

before_install:
  - npm install

script:
  - npm run build
  - each "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t yunrong/blob:latest
  - docker push yunrong/blob:latest